name: Build and Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give permission to mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_API_URL: ${{ secrets.GEMINI_API_URL }}

      # 🔥 IMPORTANT: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🚀 Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: NewIdeaAnalizer
          package: target/New-Idea-Analyzer-0.0.1-SNAPSHOT.jar
